---
name: Security check - Bandit

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Security check - Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
        with:
          python_version: ${{ matrix.python-version }}
          project_path: .
          ignore_failure: true

      - name: Security check report artifacts
        uses: actions/upload-artifact@v4.6.0
        # if: failure()
        with:
          name: secreport-${{ matrix.os }}-${{ matrix.python-version }}
          path: output/security_report.txt
